"""change abstract model

Revision ID: 03
Revises: 02
Create Date: 2025-05-05 18:03:24.471263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03'
down_revision = '02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charityproject', 'full_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('charityproject', 'invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('charityproject', 'fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('donation', 'full_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('donation', 'invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('donation', 'fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donation', 'fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('donation', 'invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('donation', 'full_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('charityproject', 'fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('charityproject', 'invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('charityproject', 'full_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
